### PR TITLE
GUI

### PR DESCRIPTION
**Pull request by TotallyNotHuman**
Discussion on this PR should be conducted here. Do not merge until ready.

### CODE REVIEW

**Comment by 0111narwhalz** [comment]
What does the GUI look like?

**Comment by TotallyNotHuman** [comment]
It's pretty much just a `JPanel` with a bunch of radio buttons. I'm going to get there.

**Comment by TotallyNotHuman** [comment]
So I got the GUI done. It looks ugly, but is functional.
Imgur
(Yes, I know the version is 'null'. Stop nitpicking.)
Note that I limited the names per generation to 100; this was due to spacing concerns. The number 2147483647 apparently does not fit on a 480x270 panel.
Thoughts?

**Comment by 0111narwhalz** [comment]
Break it to another line?

**Comment by 0111narwhalz** [comment]
Ah, I've got it. Put the number on the first line and the button below it. That should afford you the room you need.

**Comment by TotallyNotHuman** [comment]
It doesn't work that way, kerb. The box has to stay with the button.
I could just move the spinner down to the 2nd line, but I haven't figured it out yet.

**Comment by TotallyNotHuman** [comment]
Came across this during my many hours of Googling:
https://netbeans.org/kb/docs/java/gui-functionality.html
I am extremely tempted to just use this and damn the consequences, but it's really just a crutch for n00bs.
Ah well. Who cares? Nuking Main.java.

**Comment by TotallyNotHuman** [comment]
__Closed__ due to deprecation.

**Pull request closed without merging**
